name: First workflow
on: push

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
    - name: Step1
      uses: actions/checkout@v2
    - name: Step2
      run: env
    
  job2:
    name: Second Job
    runs-on: windows-latest
    steps:
    - name: Step1
      uses: actions/checkout@v2
    - name: Step2
      run: "Get-ChildItem Env:"
    
