name: Complex Worflow with dependencies
on: [push]
jobs:
  job1:
    name: Uses Ubuntu runner to print the date command
    runs-on: ubuntu-latest
    steps:
    - name: Prints the date command
      run: date
  job2:
    name: Uses Windows runner to print the date command
    runs-on: windows-latest
    steps:
    - name: Prints the date command
      run: date
  job3:
    name: Uses Mac-Os runner to print the date command
    runs-on: mac-os-latest
    steps:
    - name: Prints the date command
      run: date
  job4:
    name: Uses Ubuntu and has dependency on all three jobs
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
    - name: Prints date command when all three jobs have finished
      run: date
